### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by AryToNeX** [AryToNeX/NC-Easter-Eggs#2]
- [x] SantX Easter Egg (join, leave, onItemHeld)
- [x] Avada Kedavra Easter Egg
- [x] Tiziana "Bravoh" Easter Egg
- [x] Zio Michele Easter Egg
- [x] iPhone Sh*t Easter Egg
- [ ] Adam Kadmon Easter Egg (message)
- [ ] Pokémon Buried Alive Easter Egg (message)
- [ ] Vingardium Leviosa Easter Egg (128 y boost w/ fall damage protection)
- [ ] Thug Life Easter Egg(s)
- [ ] Owner Indrenx's Easter Egg
- [ ] More Easter Eggs
